### ISSUE TITLE
[S2 - PBI2]  Sistem pembayaran

### ISSUE THREAD

**Issue by izungb** [SI-RPL-2022/SI4302_D_TANIKUY#11]

**Comment by Caniamustika** [comment]
Proses Pembayarab
![halaman pembayaran d3](https://user-images.githubusercontent.com/84458621/164578958-c7f26589-cdd7-4029-a891-87f49c4f496c.png)
![Halaman Upload Bukti Pembayaran](https://user-images.githubusercontent.com/84458621/164578956-af26f3fb-e08c-438a-b1a7-025aa46bdc16.png)
![Halaman sukses bayar](https://user-images.githubusercontent.com/84458621/164578953-3e8b17f1-d104-4bb5-a946-6590bbf488ff.png)

**Comment by ekkynovrizalam** [comment]
Termasuk konfirmasi dari sisi admin

**Comment by Caniamustika** [comment]
Verifikasi bukti pe,bayaran - admin
![Halaman Verifikasi Bayar - Admin](https://user-images.githubusercontent.com/84458621/164586559-acec6621-1ce0-4037-ad68-9c6623647d0a.png)

**Comment by izungb** [comment]
https://user-images.githubusercontent.com/92001482/170703889-042a8c61-3b59-4bd7-a394-30136e83b6c8.mp4
