### ISSUE TITLE
[S2 - PBI1]  Mengajukan pertanyaan

### ISSUE THREAD

**Issue by izungb** [SI-RPL-2022/SI4302_D_TANIKUY#12]
User dapat mengajukan pertanyaan dengan menggunakan fitur forum diskusi

**Comment by izungb** [comment]
![Forum Diskusi 2](https://user-images.githubusercontent.com/92001482/164580140-46451d73-c390-42c7-8d88-e5308ac99e4b.png)
![Forum Diskusi](https://user-images.githubusercontent.com/92001482/164580146-bdfc05a4-6c9a-416f-a905-b1f2700de2ee.png)
![Forum Diskusi 1](https://user-images.githubusercontent.com/92001482/164580148-7c14f5ae-0fd6-4a8b-b0d2-049cf40114b9.png)

**Comment by izungb** [comment]
![image](https://user-images.githubusercontent.com/92001482/164580587-bcebceee-eb64-42d4-9757-fbd05a4daa7c.png)
![image](https://user-images.githubusercontent.com/92001482/164580687-0c978141-7b1d-481e-95fa-00c64481b4f4.png)

**Comment by ekkynovrizalam** [comment]
CRUD thread dan CRUD Comment

**Comment by izungb** [comment]
https://user-images.githubusercontent.com/92001482/170703263-c0979834-2337-4b98-90f8-ab4bce2786ac.mp4
