### ISSUE TITLE
[S3 - PBI2] Memberikan rating terhadap jawaban yang ada di forum diskusi

### ISSUE THREAD

**Issue by izungb** [SI-RPL-2022/SI4302_D_TANIKUY#15]
User dapat memberikan like dan dislike terhadap jawaban yang ada di dalam forum diskusi. Jawaban dengan like terbanyak akan otomatis naik ke urutan yang paling pertama

**Comment by izungb** [comment]
![Screenshot 2022-05-31 095353](https://user-images.githubusercontent.com/92001482/171083668-95beeac6-8b4a-4851-ae25-7095652ad240.png)

**Comment by Caniamustika** [comment]
![like dislike vpd](https://user-images.githubusercontent.com/84458621/171760964-2e513847-65db-4dcc-8478-abe32d143567.png)
Activity diagram

**Comment by Caniamustika** [comment]
Video PBI
https://user-images.githubusercontent.com/84458621/174487953-c6e0ee63-ebfc-4156-a733-27a5207674ec.mp4
