### ISSUE TITLE
[S3 - PBI5] admin dapat melihat daftar user dan melakukan delete akun user

### ISSUE THREAD

**Issue by izungb** [SI-RPL-2022/SI4302_D_TANIKUY#17]
Admin dapat melihat daftar user dan melakukan delete akun jika diperlukan

**Comment by izungb** [comment]
![list user](https://user-images.githubusercontent.com/92001482/171085200-19ff3c22-75be-4961-a003-82e8979d304d.png)

**Comment by izungb** [comment]
![list](https://user-images.githubusercontent.com/92001482/171085436-39a2445b-0366-48b7-8b76-ab786edf351c.png)

![Untitled](https://user-images.githubusercontent.com/90041853/171761016-2a183606-b0d5-4339-8098-a4276b34a6f8.png)

**Comment by bibob11** [comment]
https://user-images.githubusercontent.com/90041853/174524148-745229cf-869d-4fd1-a323-57192bc2111b.mp4
