### ISSUE TITLE
[S1 - PBI3] Mengelola assessment

### ISSUE THREAD

**Issue by izungb** [SI-RPL-2022/SI4302_D_TANIKUY#3]
Admin bisa menambah dan mengelola assesmen

**Comment by bibob11** [comment]
Use case scenario :
![ab](https://user-images.githubusercontent.com/90041853/160373506-e21d0b7d-7c37-4793-a913-ab738c3eae42.PNG)

Activity Diagram:
![bc](https://user-images.githubusercontent.com/90041853/160373662-cf95c147-fced-488f-aa08-8cceaeecefa2.PNG)

Mock Up:
![Halaman asesmen Admin](https://user-images.githubusercontent.com/90041853/160373713-97997a2f-95ae-4980-b1ef-df23da701728.png)

**Comment by ekkynovrizalam** [comment]
tambahkan untuk bisa mengelola

**Comment by izungb** [comment]
baik pak, sudah dilakukan. Terimakasih banyak

**Comment by Caniamustika** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/84458621/161172751-6a188d46-205a-40ce-8a69-71d45167bbe4.png">

Revisi Use case scenario

**Comment by Caniamustika** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/84458621/161172893-b805709a-acd0-4a1c-8a94-96e1dc5e2bd5.png">

Revisi Use Case Scenario

**Comment by izungb** [comment]
Revisi Activity diagram:

![Untitled-Page-1](https://user-images.githubusercontent.com/92001482/161186900-268e3e02-3295-42b0-8920-d12082f0caec.png)
![Untitled-Page-2](https://user-images.githubusercontent.com/92001482/161186908-e2da5b43-ccc6-48d3-9831-a049d12bba31.png)
![Untitled-Page-3](https://user-images.githubusercontent.com/92001482/161186912-2842d581-8402-4f12-8240-aa556da23a22.png)

**Comment by Caniamustika** [comment]
![image](https://user-images.githubusercontent.com/84458621/161186717-a587762c-4eae-4899-b53f-0b091e615802.png)
![image](https://user-images.githubusercontent.com/84458621/161186726-922a2a17-1b0d-4bba-899d-62ede6253501.png)


use case scenario mengedit dan hapus

**Comment by bibob11** [comment]
Revisi Mock Up:

![Halaman asesmen Admin](https://user-images.githubusercontent.com/90041853/161187425-99825563-e74f-46c7-8068-f17d30e19ba8.png)
