### ISSUE TITLE
[S1 - PBI4] Mengerjakan dan melihat nilai assessment

### ISSUE THREAD

**Issue by izungb** [SI-RPL-2022/SI4302_D_TANIKUY#4]

**Comment by bibob11** [comment]
Use Case Scenario :
![Use Case Scenario Mengerjakan dan melihat nilai Assessment](https://user-images.githubusercontent.com/90041853/161176271-cc65bd39-03cf-4474-824e-95e9cae2ef2b.PNG)

Activity Diagram :
![Activity Diagram Mengerjakan dan melihat nilai Asesmen](https://user-images.githubusercontent.com/90041853/161176098-6505ebb4-6eaa-4ec5-bb18-3c064cf1d4d3.png)

Mock Up :
![Halaman asesmen User](https://user-images.githubusercontent.com/90041853/160380354-7eb5ab71-7932-44dc-a5cb-f75e1be3f3b4.png)
![Halaman asesmen User](https://user-images.githubusercontent.com/90041853/161176885-6018b31d-27f0-4cc8-a653-f1a42af7e18b.png)
![Halaman asesmen User (1)](https://user-images.githubusercontent.com/90041853/161176893-d85030f9-42e2-40b2-a23d-fb2fc8817f62.png)

**Comment by ekkynovrizalam** [comment]
ditambahkan untuk bisa mengelola

**Comment by ekkynovrizalam** [comment]
harus di tambahkan sampai proses penilaian dan show nilai

**Comment by izungb** [comment]
sudah ditambahkan bapak, terimakasih masukkannya

**Comment by ekkynovrizalam** [comment]
diubah menjadi esai dengan ketentuan :

1. satu assessmen = satu soal
2. satu soal = satu jawaban
3. disediakan table transaksi jawaban dimana 1 jawaban mewakili 1 user

penilaian dilakukan oleh admin

**Comment by bibob11** [comment]
Revisi PBI 3 dan 4
https://user-images.githubusercontent.com/90041853/164028515-e9ded5e6-fba2-4a1a-b1a3-7b1544fb33a7.mp4
