### ISSUE TITLE
[S1 - PBI5] Mengelola paket

### ISSUE THREAD

**Issue by izungb** [SI-RPL-2022/SI4302_D_TANIKUY#5]
Admin dapat mengelola paket dimana admin dapat menggabungkan beberapa course menjadi 1 paket agar ada diskon harga

**Comment by bibob11** [comment]
User Case Scenario :
![saf](https://user-images.githubusercontent.com/90041853/160381148-3fb2a6f8-d2ac-4a18-95f0-d58dfa1e76e7.PNG)

Activity Diagram :
![rg](https://user-images.githubusercontent.com/90041853/160381301-c2c450fe-8776-4d3a-a113-f846ca4a92d4.PNG)

Mock Up :
![halaman pembayaran d1](https://user-images.githubusercontent.com/90041853/160381397-9649c295-f441-413a-a81c-c7dbba494310.png)
![halaman pembayaran d2](https://user-images.githubusercontent.com/90041853/160381411-8a1f97e5-d2ac-458e-a945-71c4ad1063bf.png)

**Comment by ekkynovrizalam** [comment]
harus ditambahkan sampai user dapat melihat history purchasenya dan valid sampai kapan

**Comment by izungb** [comment]
revisi user membeli paket menjadi admin mengelola paket

Revisi use case scenario : 
![image](https://user-images.githubusercontent.com/92001482/161180866-a0bc931b-2a62-4b4d-a051-ef0dd4f59e2b.png)
![image](https://user-images.githubusercontent.com/92001482/161180888-695063bf-8c90-4cc8-9ccb-2d7dacf1065c.png)
![image](https://user-images.githubusercontent.com/92001482/161186688-946b8b90-0a16-497f-83ee-a8eab8daa28c.png)





Revisi Mock Up :
![Dashboard admin](https://user-images.githubusercontent.com/90041853/161185848-8c6246d5-5431-49c6-a8e7-1fbf2ba17c97.png)
![Halaman Tambah Paket](https://user-images.githubusercontent.com/90041853/161185857-e186741b-83e7-4773-a3a8-4d49a15d6ef9.png)
![Edit Paket](https://user-images.githubusercontent.com/90041853/161185890-d00779ba-cf04-46c9-8001-4fcc2c9425a6.png)

**Comment by diannovitap** [comment]
![revisi1](https://user-images.githubusercontent.com/76656748/161187282-53ba79b6-cfb3-49bc-9843-ca40f4b27c49.png)
![qq](https://user-images.githubusercontent.com/76656748/161187502-bb7b2952-e02e-4bac-832e-bef5860e44ee.png)
![www](https://user-images.githubusercontent.com/76656748/161187512-c206ec1e-bf01-4599-93e1-f015ea363b11.png)
