### ISSUE TITLE
[S1 - PBI6] Membeli dan mengakses course

### ISSUE THREAD

**Issue by izungb** [SI-RPL-2022/SI4302_D_TANIKUY#6]
User dapat melakukan pembelian course untuk dapat mengaksesnya

**Comment by bibob11** [comment]
Use Case Scenario :
![ab](https://user-images.githubusercontent.com/90041853/160381667-50e7818b-47e7-4624-a900-f89b451be7bd.PNG)

Activity Diagram :
![bc](https://user-images.githubusercontent.com/90041853/160381790-3ccf0da2-630e-43fb-87bb-b06c1a569124.PNG)

Mock Up :
![Halaman Beli Course 1](https://user-images.githubusercontent.com/90041853/160381875-18b1f387-2d9c-4700-ae36-b2916cf4d0b1.png)


![Halaman Course 2](https://user-images.githubusercontent.com/90041853/160381882-fcbaafa6-06c9-4df9-8088-8bcdb65f5e72.png)

**Comment by ekkynovrizalam** [comment]
ditambahkan detail history pembelian

**Comment by izungb** [comment]
Revisi Use Case Scenario :
![scenario membeli dan mengakses course](https://user-images.githubusercontent.com/90041853/161192064-a130f2ca-aed1-4df5-9753-b1896cdc40b4.PNG)

Revisi Avticity Diagram: 
![diagram membeli dan mengakses course](https://user-images.githubusercontent.com/90041853/161193056-27233545-3107-4f83-8572-e5349d813ac8.png)


Revisi Mock up :
Detail history pembelian:
![image](https://user-images.githubusercontent.com/92001482/161177273-7b5b15e0-e893-4436-be93-df9a0f640502.png)
![image](https://user-images.githubusercontent.com/92001482/161177295-ba4813eb-e507-4d4f-b6f9-e2d890162a36.png)

**Comment by daffaasf** [comment]
![image](https://user-images.githubusercontent.com/92209841/161226597-07081f65-0751-49bf-9d06-d1d00b7aa49c.png)

**Comment by bibob11** [comment]
Revisi PBI 6
https://user-images.githubusercontent.com/90041853/164028784-a1a1dfa5-3efb-456f-abec-3e072236d43e.mp4
