### ISSUE TITLE
[S2 - PBI5] Melihat progres pembelajaran & dashboard user

### ISSUE THREAD

**Issue by izungb** [SI-RPL-2022/SI4302_D_TANIKUY#8]
User dapat melihat progres pembelajaran

**Comment by bibob11** [comment]
![Logout](https://user-images.githubusercontent.com/90041853/164579166-b6fb54d1-a200-4d7d-963c-1c8e6586d319.png)



![ad](https://user-images.githubusercontent.com/90041853/164579128-3866bf27-082f-4227-826f-75ad53ddd3f8.PNG)

**Comment by izungb** [comment]
https://user-images.githubusercontent.com/92001482/170704756-97a0d0eb-b711-4b0f-9dcd-a40214ad838a.mp4
